### ISSUE TITLE
Feature proposal: dolphin=d, elephant=e, ...

### ISSUE THREAD

**Issue by ruppde** [ariassd/crypto-animal-font#1]
hi Luis,

the font looks great but my experience with kids and crypto is, that it's no fun for them do decrypt a longer text, if the have to look up every letter <-> animal from a table. If you could put the animals on the fitting letters, e.g. dolphin=d, elephant=e, ... it would still look incomprehensible on the first look, but could be read more fluently after they've figured it out.

Would of course be kind of language dependent unless it's possible animals with the same initial letter for the major languages using the latin alphabet.

regards
arnim

**Comment by ariassd** [comment]
> hi Luis,
> 
> the font looks great but my experience with kids and crypto is, that it's no fun for them do decrypt a longer text, if the have to look up every letter <-> animal from a table. If you could put the animals on the fitting letters, e.g. dolphin=d, elephant=e, ... it would still look incomprehensible on the first look, but could be read more fluently after they've figured it out.
> 
> Would of course be kind of language dependent unless it's possible animals with the same initial letter for the major languages using the latin alphabet.
> 
> regards
> arnim

thanks for your suggestion, it sounds great, I'll work in a second version

**Comment by ruppde** [comment]
great, but keep the old one, that's still like https://en.wikipedia.org/wiki/Cryptogram = solvable with pen & paper and just harder.

just checked from https://emojipedia.org/nature/ which emoji animals have the same 1st letter in english + german. costa rica is spanish spoken?

🐜 Ant
🐻 Bear
🦫 Beaver (new emoji 13)
🦬 Bison (new emoji 13)
🐬 Dolphin
🐉 Dragon
🐘 Elephant
🐟 Fish
🦩 Flamingo (new emoji 12)
🦊 Fox
🐸 Frog
🦒 Giraffe
🦍 Gorilla
🐹 Hamster
🐝 Honeybee (both honeybee = honigbiene and bee = biene would fit, with biene=bee more common used)
🦘 Kangaroo
🐨 Koala
🐆 Leopard
🦁 Lion
🦙 Llama
🦣 Mammoth (new emoji 13)
  🦟 Mosquito
🐁 Mouse
🐙 Octopus
🦧 Orangutan (new emoji 12)
🦦 Otter (new emoji 12)
🐂 Ox
🦜 Parrot
🦚 Peacock
🐧 Penguin
🐩 Poodle
🐀 Rat
🦏 Rhinoceros
🦂 Scorpion
🦨 Skunk (new emoji 12)
🐌 Snail
🐍 Snake
🕷️ Spider
🦢 Swan
🐅 Tiger
🦖 T-Rex
🐃 Water Buffalo (rather use for B, also fits in german: büffel.)
🐋 Whale
🐺 Wolf
🦓 Zebra

♓ ℰ Ŷ ,     ☪️ 🃑 🅽     ℬ モ     ⛎ 💲 モ 🌛     ᚩ 🍩 ℛ     ⚡ 🍩 ₥ € ᵺ ༐ 🆖     ⚡ ༐ ㏕ 🅰️ Ɽ     🆃 ⭕     ᵺ 🕕 ى     ; ) 
(http://rupp.de/crypto_puzzles/crypto_puzzles_web.py)
Would need to avoid the new emoji where possible, kids devices are sometimes rather old. 

After the kids have solved the font on paper, another way would be to give the kids an USB stick with a .docx and hint to the easy solution of switching the font back to arial ;)

**Comment by ariassd** [comment]
> great, but keep the old one, that's still like https://en.wikipedia.org/wiki/Cryptogram = solvable with pen & paper and just harder.
> 
> just checked from https://emojipedia.org/nature/ which emoji animals have the same 1st letter in english + german. costa rica is spanish spoken?
> 
> 🐜 Ant
> 🐻 Bear
> 🦫 Beaver (new emoji 13)
> 🦬 Bison (new emoji 13)
> 🐬 Dolphin
> 🐉 Dragon
> 🐘 Elephant
> 🐟 Fish
> 🦩 Flamingo (new emoji 12)
> 🦊 Fox
> 🐸 Frog
> 🦒 Giraffe
> 🦍 Gorilla
> 🐹 Hamster
> 🐝 Honeybee (both honeybee = honigbiene and bee = biene would fit, with biene=bee more common used)
> 🦘 Kangaroo
> 🐨 Koala
> 🐆 Leopard
> 🦁 Lion
> 🦙 Llama
> 🦣 Mammoth (new emoji 13)
> 🦟 Mosquito
> 🐁 Mouse
> 🐙 Octopus
> 🦧 Orangutan (new emoji 12)
> 🦦 Otter (new emoji 12)
> 🐂 Ox
> 🦜 Parrot
> 🦚 Peacock
> 🐧 Penguin
> 🐩 Poodle
> 🐀 Rat
> 🦏 Rhinoceros
> 🦂 Scorpion
> 🦨 Skunk (new emoji 12)
> 🐌 Snail
> 🐍 Snake
> 🕷️ Spider
> 🦢 Swan
> 🐅 Tiger
> 🦖 T-Rex
> 🐃 Water Buffalo (rather use for B, also fits in german: büffel.)
> 🐋 Whale
> 🐺 Wolf
> 🦓 Zebra
> 
> ♓ ℰ Ŷ , ☪️ 🃑 🅽 ℬ モ ⛎ 💲 モ 🌛 ᚩ 🍩 ℛ ⚡ 🍩 ₥ € ᵺ ༐ 🆖 ⚡ ༐ ㏕ 🅰️ Ɽ 🆃 ⭕ ᵺ 🕕 ى ; )
> (http://rupp.de/crypto_puzzles/crypto_puzzles_web.py)
> Would need to avoid the new emoji where possible, kids devices are sometimes rather old.
> 
> After the kids have solved the font on paper, another way would be to give the kids an USB stick with a .docx and hint to the easy solution of switching the font back to arial ;)

Thank you, actually I have made some new icons, and I think I have all I need for the new font. I'm going to release as soon as posible.

**Comment by ariassd** [comment]
There are some changes you may like, I worked in a version to sort icons with english alphabet.

Make them match in several languages could be little difficult but I'm going to analyse a way to do it. I'll work in that when I have some free time for now is what I can offer to you.

I saw your project and I love it, it looks great, I really hope this font would help you to achieve your target.

**Comment by ruppde** [comment]
Thanks, 

I like seastar=5 and spider=8 ;) Hard to come up with more like it. 6 could be any insect, 4 some mamal, 2 gorilla? 

A cat has 9 lifes.
Unicorn, rhino 1

centipede= :100:
